// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYFHatiqCfZNodb-LQIVorCP-_qnqgbXo',
    appId: '1:459314018601:web:e250028ac63c14abe19f38',
    messagingSenderId: '459314018601',
    projectId: 'localpass-3ef5f',
    authDomain: 'localpass-3ef5f.firebaseapp.com',
    storageBucket: 'localpass-3ef5f.firebasestorage.app',
    measurementId: 'G-38X7N0EHYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUc9lVoqqnTaJmkZigMwjgHt3DDelpzvI',
    appId: '1:459314018601:android:62fe9c3973ea8d04e19f38',
    messagingSenderId: '459314018601',
    projectId: 'localpass-3ef5f',
    storageBucket: 'localpass-3ef5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAS6w8mvDKg8ybogjrO-9adHhKW7frMd0',
    appId: '1:459314018601:ios:9af25f83cc924380e19f38',
    messagingSenderId: '459314018601',
    projectId: 'localpass-3ef5f',
    storageBucket: 'localpass-3ef5f.firebasestorage.app',
    iosBundleId: 'com.example.localpass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAS6w8mvDKg8ybogjrO-9adHhKW7frMd0',
    appId: '1:459314018601:ios:9af25f83cc924380e19f38',
    messagingSenderId: '459314018601',
    projectId: 'localpass-3ef5f',
    storageBucket: 'localpass-3ef5f.firebasestorage.app',
    iosBundleId: 'com.example.localpass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYFHatiqCfZNodb-LQIVorCP-_qnqgbXo',
    appId: '1:459314018601:web:2632ab18b7c773c4e19f38',
    messagingSenderId: '459314018601',
    projectId: 'localpass-3ef5f',
    authDomain: 'localpass-3ef5f.firebaseapp.com',
    storageBucket: 'localpass-3ef5f.firebasestorage.app',
    measurementId: 'G-YH056D1P7G',
  );
}
